### ISSUE TITLE
consider making moc-lyrics script executable

### ISSUE THREAD

**Issue by donm** [hakerdefo/moc-lyrics#1]
Thanks for making this--this is fantastic.

Is there a reason to not make the moc-lyrics script executable in the git repository?  Rather than downloading repos and copying scripts into my PATH, I like to clone the repo and put make symlinks to any executables.  But changing the permissions on the symlink makes the local copy of the repo dirty.

**Comment by hakerdefo** [comment]
There is no reason! Infact it never occured to me! Thanks for the idea! I will implement this at earliest with all of my scripts on GitHub!
Cheers!!!
